StockMaster/StockMaster_app/urls.py
from django.urls import path     
from StockMaster_app import views

app_name = 'SM_app'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/profile', views.profile, name='profile'),
    ########## Log and register #######################
    path('signup/', views.signup_page, name='signup-page'),
    path('login/', views.signin_page, name='signin-page'),
    path('register', views.register, name='registrProcess'),
    path('loging', views.login, name="loginProcess"),
    path('register', views.register, name='registrProcess'),
    path('loging', views.login, name="loginProcess"),
    ############### End LOG AND REG PROCESS ############
    ####### Prodcut Part ###############################
    path('display_products/<user_id>', views.display_products),
    path('save_products/', views.save_products, name='save_products'),
    # path('add_product', views.add_prodcut),
    ############# End product pathes ###################
]
    

StockMaster/StockMaster_app/models.py
from django.db import models
import re 

class UserManager(models.Manager):
    def regValidator(self, postData):
        errors = {}
        #input validations
        if len(postData['f_name']) < 2:
            errors['f_name'] = "First Name should at least be 2 charecters"
        if len(postData['l_name']) < 2:
            errors['l_name'] = "Last Name should at least be 2 charecters"
        if len(postData['s_name']) < 2:
            errors['s_name'] = "Store Name should at least be 2 charecters"
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):    # test whether a field matches the pattern            
            errors['email'] = "Invalid email address!"
        if User.objects.filter(email=postData['email']).exists():
            errors['email'] = "This email is already registered!"
        if len(postData['password'] or postData['password_conf']) < 8:
            errors['password_len'] = "Password should atleast be 8 charecters"
        if postData['password'] != postData['password_conf']:
            errors['password_match'] = "Passwords do not match"
        return errors 

    def loginValidator(self, postData):
        errors = {}  
        if not (User.objects.filter(email=postData['email']) and User.objects.filter(password=postData['password'])):
            errors['login'] = "Login failed! Check email and password"

        return errors 

class User(models.Model):
    f_name = models.CharField(max_length=255)
    l_name = models.CharField(max_length=255)
    s_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager() 
      
class Product(models.Model): 
    p_name = models.CharField(max_length=255)
    p_barcode = models.IntegerField()
    expire_date = models.DateTimeField()
    cost = models.FloatField()
    qty = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #orders_list

class Order(models.Model): 
    p_price = models.FloatField()
    qty_sell = models.IntegerField()
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Order_list(models.Model): 
    p_price = models.FloatField()
    qty_sell = models.IntegerField()
    products = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders_list')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

StockMaster/StockMaster_app/views.py
from django.shortcuts import render, redirect, reverse
from .models import *
# from .models import Prodcuts 
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


# This function renders the homepage
def homepage(request):
    return render(request, 'homepage.html')

#This function renders the User Profile page upon button click
def profile(request):
    return render(request, 'users-profile.html')

#This function renders the dashboard after the user logs in to his acoount
def dashboard(request):
    context = {
    'username' :  request.session['user'],
    'user' : User.objects.get(id=request.session['user'])
    }
    return render(request, 'dashboard.html', context)

################## Registration and Loging ################
#This function renders the sign up page upon button click
def signup_page(request):
    return render(request, 'pages-register2.html')

#This function for registration process
def register(request):
    errors = User.objects.regValidator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/signup')
    else:
        User.objects.create(
        f_name= request.POST['f_name'], 
        l_name= request.POST['l_name'], 
        s_name= request.POST['s_name'], 
        email=request.POST['email'], 
        password=request.POST['password'])
        return render(request, 'pages-login.html')

#This function renders the Log In page upon button click
def signin_page(request):
    return render(request, 'pages-login.html')

#This function for loging process
def login(request):
    errors = User.objects.loginValidator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return render(request, 'pages-login.html')
    else:
        user = User.objects.get(email = request.POST['email'])
        request.session['user'] = user.id
        request.session['username'] = user.f_name
        return redirect('/dashboard')
################# This is for Prodcut ####################################
#This function renders the page that displays all products in the database
def display_products(request, user_id):
    context = {
        'user' : User.objects.get(id=user_id)
    }
    return render(request, 'display_products-page.html', context)



def save_products(request):
    try:
        if request.method == 'POST':
            data = request.POST.get('data')
            try:
                products = json.loads(data)
                # Save products to the database
                for product in products:
                    new_product = Product(
                        p_name=product['p_name'],
                        p_barcode=int(product['p_barcode']),
                        expire_date=product['expire_date'],
                        cost=int(product['cost']),
                        qty=int(product['qty']),
                        user=User.objects.get(id=request.session.get('user'))
                    )
                    new_product.save()

                return JsonResponse({'message': 'Products saved successfully'})
            except Exception as e:
                return JsonResponse({'error': 'Error saving products: ' + str(e)}, status=500)
    except Exception as e:
        return JsonResponse({'error': 'Invalid request method'}, status=400)

StockMaster/StockMaster_app/templates/display_products-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/products.js' %}"></script>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>StockMaster</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/products.js' %}"></script>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <script src="">

    </script>

    <!-- <script src="https://code.jquery.com/jquery-3.6.0.js"></script> -->

    <script src="../static/js/products.js"></script>
    <!-- Favicons -->
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/quill/quill.snow.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/quill/quill.bubble.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/simple-datatables/style.css' %}">
    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        .btn-orange {
            color: white;
            background-color: orange;
        }

        h1,
        h3 {
            text-align: center;
            color: red;
        }
    </style>
</head>

<body>
    <script>
        const saveProductsUrl = "{% url 'SM_app:save_products' %}";
    </script>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a href="#" class="logo d-flex align-items-center">
                <img src="{% static 'img/logo.png' %}" alt="">
                <span class="d-none d-lg-block">StockMaster</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div>
        <!-- End Logo -->
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                </li>
                <!-- End Notification Nav -->
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow Profile">
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                </ul>
                <!-- End Profile Dropdown Items -->
                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{user.f_name}} {{user.l_name}}</span>
                    </a>
                    <!-- End Profile Iamge Icon -->
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{user.f_name}} {{user.l_name}}</h6>
                            <span>General Manager</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="/dashboard/profile">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>
                    </ul>
                    <!-- End Profile Dropdown Items -->
                </li>
                <!-- End Profile Nav -->
            </ul>
        </nav>
        <!-- End Icons Navigation -->
    </header>
    <!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link " href="index.html">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="index.html">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- End Dashboard Nav -->
            ç
            <!-- End Profile Page Nav -->
            <!-- End F.A.Q Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="customers-page.html">
                    <i class="bi bi-envelope"></i>
                    <span>Customers</span>
                </a>
            </li>
            <!-- End Contact Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="orders-page.html">
                    <i class="bi bi-card-list"></i>
                    <span>Orders</span>
                </a>
            </li>
            <!-- End Orders Page Nav -->
        </ul>
    </aside>
    <!-- End Sidebar-->
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Products</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Products</li>
                </ol>
            </nav>
        </div>
        <!-- End Page Title -->
        <section class="section dashboard">
            <div class="row">
                <div class="col-sm-12">
                    <form id="product_form" onsubmit="return handleAddProductForm(event)">
                        {% csrf_token %}
                        <!-- product Name  -->
                        <div class="row justify-content-center mb-3">
                            <div class="col-sm-2 text-center fw-bold ">
                                <label class="form-label">Product Name:</label>
                            </div>
                            <div class="col-sm-4">
                                <input id="p_name" type="text" class="form-control" name="p_name">
                            </div>
                        </div>
                        <!-- Product barcode -->
                        <div class="row justify-content-center mb-3">
                            <div class="col-sm-2 text-center fw-bold ">
                                <label class="form-label">Barcode</label>
                            </div>
                            <div class="col-sm-4">
                                <input id="p_barcode" type="number" class="form-control" name="p_barcode">
                            </div>
                        </div>
                        <!-- Product Price -->
                        <div class="row justify-content-center mb-3">
                            <div class="col-sm-2 text-center fw-bold ">
                                <label class="form-label">Product Price:</label>
                            </div>
                            <div class="col-sm-4">
                                <input id="cost" type="number" class="form-control" name="cost">
                            </div>
                        </div>
                        <!-- Quantity -->
                        <div class="row justify-content-center mb-3">
                            <div class="col-sm-2 text-center fw-bold ">
                                <label class="form-label">Quantity</label>
                            </div>
                            <div class="col-sm-4">
                                <input id="qty" type="number" class="form-control" name="qty">
                            </div>
                        </div>
                        <!-- Expire_date -->
                        <div class="row justify-content-center mb-3">
                            <div class="col-sm-2 text-center fw-bold ">
                                <label class="form-label">Expire Date</label>
                            </div>
                            <div class="col-sm-4">
                                <input id='expire_date' type="date" class="form-control" name="expire_date">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12 text-center">
                                <button type="submit" class="btn btn-primary">Add Product</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-12">
                    <div class="card top-selling overflow-auto">
                        <div class="card-body pb-0">
                            <br>
                            <a id="saveBtn" data-url="{% url 'SM_app:save_products' %}" onclick="save_all_products()"
                                class="btn btn-primary rounded-pill">Save</a>
                            <!-- <a href="/dashboard/products/add_new" class="btn btn-primary rounded-pill">+ Add Product</a> -->
                            <table class="table table-borderless" id="products_table">
                                <thead>
                                    <tr>
                                        <th scope="col">Product Name</th>
                                        <th scope="col">Barcode</th>
                                        <th scope="col">Product Price</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Expire Date</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="products"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- End Top Selling -->
            </div>
            </div>
            <!-- End Left side columns -->
            <!-- Right side columns -->
            </div>
            <div id="csrfToken" data-csrf="{{ csrf_token }}"></div>
        </section>
    </main>
    <!-- End #main -->
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>
</body>

</html>

StockMaster/StockMaster_app/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>StockMaster</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/quill/quill.snow.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/quill/quill.bubble.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/simple-datatables/style.css' %}">

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <style>
        .btn-orange {
            color: white;
            background-color: orange;
        }

        h1,
        h3 {
            text-align: center;
        }
    </style>
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="/" class="logo d-flex align-items-center">
                <img src="{% static 'img/logo.png' %}" alt="">
                <span class="d-none d-lg-block">StockMaster</span>
            </a>
        </div><!-- End Logo -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown">
                    <a class="nav-link nav-icon" href="/signup">
                        <button type="button" class="btn btn-primary rounded-pill">Create Account</button>
                    </a><!-- End Create account btn -->

                </li><!-- End Notification Nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link nav-icon" href="/login">
                        <button type="button" class="btn btn-success rounded-pill">Log In</button>
                    </a><!-- End Log In Icon -->
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <main id="main" class="main">
        <h1 class="display-1">StockMaster</h1>
        <h3 class="display-4">No Stock Wasted</h3>
        <div class="text-center">
            <a href="/signup" class="btn btn-orange">Start your 14-day Free Trial</a>
        </div>

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>StockMaster</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
</body>


</html>

StockMaster/StockMaster_app/templates/pages-login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/register.css' %}">
  <title>Login | StockMaster</title>
</head>

<body>

  <main>
    <form action="{% url 'SM_app:loginProcess' %}" , method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td>Email:</td>
          <td><input type="text" name="email"></td>
        </tr>
        <tr>
          <td>Password:</td>
          <td><input type="password" name="password"></td>
        </tr>
        <tr>
          <td><input type="submit" value="submit"></td>
        </tr>
      </table>
    </form>
  </main>
  <div id="error_messages">
    {% if messages %}
    <ul style="color: red; list-style-type: none;">
      {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>

</body>

</html>

StockMaster/StockMaster_app/templates/pages-register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <link rel="stylesheet" href="{% static 'css/register.css' %}">
  <title>Registeration | StockMaster </title>
</head>

<body>

  <main>
    <form action="{% url 'SM_app:registrProcess' %}" method="POST">
      {% csrf_token %}
      <table>
        <th colspan="2">
          Create Account
        </th>
        <tr>
          <td>First Name:</td>
          <td><input type="text" name="f_name"></td>
        </tr>
        <tr>
          <td>Last Name:</td>
          <td><input type="text" name="l_name"></td>
        </tr>
        <tr>
          <td>Store Name:</td>
          <td><input type="text" name="s_name"></td>
        </tr>
        <tr>
          <td>Email:</td>
          <td><input type="text" name="email"></td>
        </tr>
        <tr>
          <td>Password:</td>
          <td><input type="password" name="password"></td>
        </tr>
        <tr>
          <td>Password Confirm:</td>
          <td><input type="password" name="password_conf"></td>
        </tr>
        <tr colspan="2">
          <td><input type="submit" value="Create Accuont"></td>
        </tr>
      </table>
    </form>
  </main>
  <div id="error_messages">
    {% if messages %}
    <ul style="color: red; list-style-type: none;">
      {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>

</body>

</html>